### ISSUE TITLE
Group Ptoject 3:  Popular Reddit Posts Viewer with Fetch API and Async/Await

### ISSUE THREAD

**Issue by uniquemozilla22** [yogeshtakeo/Fetch_Todo#3]
Topics Covered:

` JS Async / Await , JS Advance Concepts `

Task:
Create a webpage that fetches data from the
"https://www.reddit.com/r/popular.json" link using the Fetch API with `async/await` syntax. Display the results on the webpage using HTML and CSS, such that each post's title, author, and image  (if available) are shown in separate elements. Use JavaScript to manipulate  the DOM and insert the fetched data into the appropriate HTML elements.

Additionally, implement a search bar on the webpage that allows users to search for posts containing specific keywords. When the  enters a search term and submits the form, use JavaScript to filter the displayed posts to show only those that match the search criteria.

**Comment by yogeshtakeo** [comment]
Team 1: @sushilkhanal  @kenneth-ee-t 

Its good implementation and the code is correct :

Marks :10 



![Image](https://user-images.githubusercontent.com/128008784/235370918-94ba6cfe-120d-426b-97e9-d76334cff856.png)


![Image](https://user-images.githubusercontent.com/128008784/235370927-72a63761-871a-45a7-9ba2-1608894c0a3a.png)


![Image](https://user-images.githubusercontent.com/128008784/235370934-59cd7b66-3df8-4163-a14e-89fda6af3740.png)

**Comment by yogeshtakeo** [comment]
Team 2 : @sushilkhanal @jyotibaskota 

Implementation is correct and Tasks are fullfilled 

Marks : 10

![image](https://user-images.githubusercontent.com/128008784/235371749-2198c366-2d2a-47d8-93ea-21eb44b3a815.png)
![image](https://user-images.githubusercontent.com/128008784/235371770-bb2392a2-b1ad-4ddc-9c63-caf0a9d48033.png)

**Comment by yogeshtakeo** [comment]
Team 3: @jayaprakashshrestha @Bhabishaphuyal6 

Good implementation of the API

Marks : 10

![Image](https://user-images.githubusercontent.com/128008784/235375348-000597bd-ac46-4dd9-a366-ec55b17fd29e.png)
